; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
#NoTrayIcon
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 28
Gui Font, s16 Bold, Segoe UI
Gui Add, Text, x121 y41 w487 h123 +0x200 +Center, Welcome to the SakuraArcade installer!
Gui Font
Gui Font, s13, Segoe UI
Gui Add, Text, x190 y131 w350 h23 +0x200 +Center, What would you like to do?
Gui Font
Gui Add, Button, x315 y227 w100 h45, Install SakuraArcade
Gui Add, Button, x196 y303 w100 h45 +Disabled, Uninstall SakuraArcade
Gui Add, Button, x433 y303 w100 h45 +Disabled, Modify installation
Gui Add, Text, x8 y403 w211 h23 +0x200, Version 1.0 - Developed by hajimedajime86
Gui Add, Button, x653 y404 w69 h23, Licence

Gui Show, w730 h432, SakuraArcade Installer 1.0
Return

ButtonLicence:
Run, "https://www.gnu.org/licenses/gpl-3.0.en.html"
Return





GuiEscape:
GuiClose:
    ExitApp
